package by;

import com.sun.org.apache.xalan.internal.templates.Constants;
import com.sun.org.apache.xpath.internal.compiler.Keywords;
import javax.management.JMX;

/* loaded from: TunerStudioMS.jar:by/n.class */
public class n {
    public static m a() {
        b bVar = new b();
        k kVar = new k("smoothBasic");
        kVar.a(new l("fieldName"));
        kVar.a(new l("smoothingFactor"));
        bVar.a(kVar);
        k kVar2 = new k("smoothFiltered");
        kVar2.a(new l("val"));
        bVar.a(kVar2);
        k kVar3 = new k("abs");
        kVar3.a(new l("val"));
        bVar.a(kVar3);
        k kVar4 = new k("sqrt");
        kVar4.a(new l("val"));
        bVar.a(kVar4);
        k kVar5 = new k(Keywords.FUNC_ROUND_STRING);
        kVar5.a(new l("val"));
        bVar.a(kVar5);
        k kVar6 = new k("ceil");
        kVar6.a(new l("val"));
        bVar.a(kVar6);
        k kVar7 = new k(Keywords.FUNC_FLOOR_STRING);
        kVar7.a(new l("val"));
        bVar.a(kVar7);
        k kVar8 = new k("recip");
        kVar8.a(new l("val"));
        bVar.a(kVar8);
        k kVar9 = new k("pow");
        kVar9.a(new l("val"));
        kVar9.a(new l("exponent"));
        bVar.a(kVar9);
        k kVar10 = new k("isNaN");
        kVar10.a(new l("val"));
        bVar.a(kVar10);
        k kVar11 = new k("exp");
        kVar11.a(new l("val"));
        bVar.a(kVar11);
        k kVar12 = new k("log");
        kVar12.a(new l("val"));
        bVar.a(kVar12);
        k kVar13 = new k("log10");
        kVar13.a(new l("val"));
        bVar.a(kVar13);
        k kVar14 = new k("lastValue");
        kVar14.a(new l("anyField"));
        bVar.a(kVar14);
        k kVar15 = new k("historicalValue");
        kVar15.a(new l("anyField"));
        kVar15.a(new l("recordsBack"));
        bVar.a(kVar15);
        k kVar16 = new k("accumulate");
        kVar16.a(new l("anyField"));
        bVar.a(kVar16);
        k kVar17 = new k("persistentAccumulate");
        kVar17.a(new l("anyField"));
        bVar.a(kVar17);
        k kVar18 = new k(JMX.MAX_VALUE_FIELD);
        kVar18.a(new l("anyField"));
        bVar.a(kVar18);
        k kVar19 = new k(JMX.MIN_VALUE_FIELD);
        kVar19.a(new l("anyField"));
        bVar.a(kVar19);
        k kVar20 = new k("min");
        kVar20.a(new l("expression"));
        kVar20.a(new l("expression"));
        kVar20.a(new l("..."));
        bVar.a(kVar20);
        k kVar21 = new k("max");
        kVar21.a(new l("expression"));
        kVar21.a(new l("expression"));
        kVar21.a(new l("..."));
        bVar.a(kVar21);
        k kVar22 = new k("accelHp");
        kVar22.a(new l("velocityMPH"));
        kVar22.a(new l("deltaVelocityHPH"));
        kVar22.a(new l("deltaTimeSec"));
        kVar22.a(new l("weightLB"));
        bVar.a(kVar22);
        k kVar23 = new k("aerodynamicDragHp");
        kVar23.a(new l("velocity"));
        kVar23.a(new l("airDensity"));
        kVar23.a(new l("dragCoefficent"));
        kVar23.a(new l("frontalArea"));
        bVar.a(kVar23);
        k kVar24 = new k("rollingDragHp");
        kVar24.a(new l("speedMPH"));
        kVar24.a(new l("tirePressure"));
        kVar24.a(new l("weightLB"));
        bVar.a(kVar24);
        k kVar25 = new k("sin");
        kVar25.a(new l("val"));
        bVar.a(kVar25);
        k kVar26 = new k("cos");
        kVar26.a(new l("val"));
        bVar.a(kVar26);
        k kVar27 = new k("asin");
        kVar27.a(new l("val"));
        bVar.a(kVar27);
        k kVar28 = new k("acos");
        kVar28.a(new l("val"));
        bVar.a(kVar28);
        k kVar29 = new k("tan");
        kVar29.a(new l("val"));
        bVar.a(kVar29);
        k kVar30 = new k("atan");
        kVar30.a(new l("val"));
        bVar.a(kVar30);
        bVar.a(new k("isOnline"));
        bVar.a(new k("isAdvancedMathAvailable"));
        bVar.a(new k("getLogTime"));
        k kVar31 = new k("table");
        kVar31.a(new l("val"));
        kVar31.a(new l("incFileName"));
        bVar.a(kVar31);
        k kVar32 = new k("tableLookup");
        kVar32.a(new l("array.valueArrayName"));
        kVar32.a(new l("array.lookupArrayName"));
        kVar32.a(new l("lookupChannelName"));
        bVar.a(kVar32);
        k kVar33 = new k("tableLookup");
        kVar33.a(new l("array.zParamName"));
        kVar33.a(new l("array.xParamName"));
        kVar33.a(new l("array.yParamName"));
        kVar33.a(new l("xChannelName"));
        kVar33.a(new l("yChannelName"));
        bVar.a(kVar33);
        bVar.a(new k("timeNow"));
        k kVar34 = new k("selectExpression");
        kVar34.a(new l("indexExpression"));
        kVar34.a(new l("expression0"));
        kVar34.a(new l("expression1"));
        kVar34.a(new l("expressionN"));
        bVar.a(kVar34);
        k kVar35 = new k("arrayValue");
        kVar35.a(new l("ArrayCalParameter"));
        kVar35.a(new l("indexExpression"));
        bVar.a(kVar35);
        k kVar36 = new k(Constants.ELEMNAME_IF_STRING);
        kVar36.a(new l(Constants.ATTRNAME_CONDITION));
        kVar36.a(new l("thenExp"));
        kVar36.a(new l("elseExp"));
        bVar.a(kVar36);
        k kVar37 = new k(Keywords.FUNC_SUM_STRING);
        kVar37.a(new l("exp0"));
        kVar37.a(new l("exp1"));
        kVar37.a(new l("expN..."));
        bVar.a(kVar37);
        k kVar38 = new k("toggle");
        kVar38.a(new l("expression"));
        l lVar = new l("initVal");
        lVar.a(true);
        kVar38.a(lVar);
        bVar.a(kVar38);
        return bVar;
    }
}
