package sun.util.resources.cldr.mer;

import sun.util.resources.OpenListResourceBundle;

/* loaded from: cldrdata.jar:sun/util/resources/cldr/mer/CurrencyNames_mer.class */
public class CurrencyNames_mer extends OpenListResourceBundle {
    /* JADX WARN: Type inference failed for: r0v1, types: [java.lang.Object[], java.lang.Object[][]] */
    @Override // sun.util.resources.OpenListResourceBundle
    protected final Object[][] getContents() {
        return new Object[]{new Object[]{"KES", "Ksh"}, new Object[]{"aed", "Dirham ya Falme cia Kiarabu"}, new Object[]{"aoa", "Kwanza ya Angola"}, new Object[]{"aud", "Dola ya Austrĩlia"}, new Object[]{"bhd", "Dinari ya Baharini"}, new Object[]{"bif", "Faranga ya Burundi"}, new Object[]{"bwp", "Pula ya Botswana"}, new Object[]{"cad", "Dola ya Kanada"}, new Object[]{"cdf", "Faranga ya Kongo"}, new Object[]{"chf", "Faranga ya Swisilandi"}, new Object[]{"cny", "Yuan Renminbi ya China"}, new Object[]{"cve", "Eskudo ya Kepuvede"}, new Object[]{"djf", "Faranga ya Jibuti"}, new Object[]{"dzd", "Dinari ya Anjĩria"}, new Object[]{"egp", "Paũndi ya Misri"}, new Object[]{"ern", "Nakfa ya Eritrea"}, new Object[]{"etb", "Bĩrũ ya Ithiopia"}, new Object[]{"eur", "Yuro"}, new Object[]{"gbp", "Paũndi ya Ngeretha"}, new Object[]{"ghc", "Sedi ya Ghana"}, new Object[]{"gmd", "Dalasi ya Gambia"}, new Object[]{"gns", "Faranga ya Gine"}, new Object[]{"inr", "Rupia ya India"}, new Object[]{"jpy", "Sarafu ya japani"}, new Object[]{"kes", "Shilingi ya Kenya"}, new Object[]{"kmf", "Faranga ya Komoro"}, new Object[]{"lrd", "Dola ya Liberia"}, new Object[]{"lsl", "Loti ya Lesoto"}, new Object[]{"lyd", "Dinari ya Libya"}, new Object[]{"mad", "Dirham ya Moroko"}, new Object[]{"mga", "Ariarĩ ya Bukini"}, new Object[]{"mro", "Ugwiya ya Mauritania"}, new Object[]{"mur", "Rupia ya Maurĩtiasi"}, new Object[]{"mwk", "Kwacha ya Malawi"}, new Object[]{"mzm", "Metikali ya Mozambĩkĩ"}, new Object[]{"nad", "Dola ya Namibia"}, new Object[]{"ngn", "Naira ya Nijeria"}, new Object[]{"rwf", "Faranga ya Rwanda"}, new Object[]{"sar", "Riyal ya Saudi Arĩbia"}, new Object[]{"scr", "Rupia ya Shelisheli"}, new Object[]{"sdg", "Paũndi ya Sudani"}, new Object[]{"shp", "Paũndi ya Santahelena"}, new Object[]{"sll", "Leoni"}, new Object[]{"sos", "Shilingi ya Somalia"}, new Object[]{"std", "Dobra ya Sao Tome na Principe"}, new Object[]{"szl", "Lilangeni"}, new Object[]{"tnd", "Dinari ya Tunisia"}, new Object[]{"tzs", "Shilingi ya Tanzania"}, new Object[]{"ugx", "Shilingi ya Uganda"}, new Object[]{"usd", "Dola ya Amerika"}, new Object[]{"xaf", "Faranga CFA BEAC"}, new Object[]{"xof", "Faranga CFA BCEAO"}, new Object[]{"zar", "Randi ya Afrika ya Sauthi"}, new Object[]{"zmk", "Kwacha ya Zambia"}, new Object[]{"zwd", "Dola ya Zimbabwe"}};
    }
}
