package sun.text.resources.hr;

import sun.util.resources.OpenListResourceBundle;

/* loaded from: localedata.jar:sun/text/resources/hr/JavaTimeSupplementary_hr.class */
public class JavaTimeSupplementary_hr extends OpenListResourceBundle {
    /* JADX WARN: Type inference failed for: r0v1, types: [java.lang.Object[], java.lang.Object[][]] */
    @Override // sun.util.resources.OpenListResourceBundle
    protected final Object[][] getContents() {
        return new Object[]{new Object[]{"QuarterAbbreviations", new String[]{"1kv", "2kv", "3kv", "4kv"}}, new Object[]{"QuarterNames", new String[]{"1. kvartal", "2. kvartal", "3. kvartal", "4. kvartal"}}, new Object[]{"QuarterNarrows", new String[]{"1.", "2.", "3.", "4."}}, new Object[]{"calendarname.buddhist", "budistički kalendar"}, new Object[]{"calendarname.gregorian", "gregorijanski kalendar"}, new Object[]{"calendarname.gregory", "gregorijanski kalendar"}, new Object[]{"calendarname.islamic", "islamski kalendar"}, new Object[]{"calendarname.islamic-civil", "islamski civilni kalendar"}, new Object[]{"calendarname.islamicc", "islamski civilni kalendar"}, new Object[]{"calendarname.japanese", "japanski kalendar"}, new Object[]{"calendarname.roc", "kalendar Republike Kine"}, new Object[]{"field.dayperiod", "dio dana"}, new Object[]{"field.era", "era"}, new Object[]{"field.hour", "sat"}, new Object[]{"field.minute", "minuta"}, new Object[]{"field.month", "mjesec"}, new Object[]{"field.second", "sekunda"}, new Object[]{"field.week", "tjedan"}, new Object[]{"field.weekday", "dan u tjednu"}, new Object[]{"field.year", "godina"}, new Object[]{"field.zone", "zona"}, new Object[]{"java.time.buddhist.DatePatterns", new String[]{"EEEE, d. MMMM y. G", "d. MMMM y. G", "d. M. y. G", "d.M.y."}}, new Object[]{"java.time.japanese.DatePatterns", new String[]{"EEEE, d. MMMM y. G", "d. MMMM y. G", "d. M. y. G", "d.M.y. G"}}, new Object[]{"java.time.japanese.long.Eras", new String[]{"poslije Krista", "Meiji", "Taishō", "Shōwa", "Heisei", "Reiwa"}}, new Object[]{"java.time.japanese.short.Eras", new String[]{"p. Kr.", "Meiji", "Taishō", "Shōwa", "Heisei", "Reiwa"}}, new Object[]{"java.time.long.Eras", new String[]{"Prije Krista", "Poslije Krista"}}, new Object[]{"java.time.roc.DatePatterns", new String[]{"EEEE, d. MMMM y. G", "d. MMMM y. G", "d. M. y. G", "d.M.y. G"}}, new Object[]{"java.time.short.Eras", new String[]{"Prije Krista", "Poslije Krista"}}, new Object[]{"roc.DatePatterns", new String[]{"EEEE, d. MMMM y. GGGG", "d. MMMM y. GGGG", "d. M. y. GGGG", "d.M.y. GGGG"}}, new Object[]{"roc.Eras", new String[]{"prije R.O.C.", "R.O.C."}}, new Object[]{"roc.short.Eras", new String[]{"prije R.O.C.", "R.O.C."}}};
    }
}
